name: Build Android APK

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Legacy JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x android/gradlew

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --stacktrace

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bplog-app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
